name: Release

on:
  release:
    types: [created]
    tags-ignore:
      - 'qcli*.*.*'

jobs:
  build:
    if: ${{ !startsWith(github.event.release.name, 'qcli') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Log GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
